### ISSUE TITLE
how to prevent bracket with red background

### ISSUE THREAD

**Issue by easyfrog** [corneliusio/svelte-sublime#19]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/10724325/139566381-9f06f11a-f6b7-42b0-919a-b5184fd047a2.png">

I don't know why should this happend. and how to prevent it?

**Comment by corneliusio** [comment]
Want to apologize for my absence on this project for the last few months. I've been extremely overloaded with my full-time work since the beginning of the year and it has made it impossible to address these issues in a timely manner. That said, things are leveling back out now and I will be addressing this and other issues in the next week or two.

Appreciate everyone's patients as I know how frustrating it can feel to be at the mercy of an open-source project that isn't keeping up with changes and fixes without any real recourse. This repo is not abandoned and I will absolutely be continuing to maintain it for the foreseeable future.

**Comment by corneliusio** [comment]
Fixes for this have been deployed and can be accessed at https://github.com/corneliusio/svelte-sublime/releases/tag/st4-3.5.0 if you're interested in downloading manually.

Due to changes to the package control channel, I was forced to submit an update to them as well to handle releases for ST3 and ST4 respectively. https://github.com/wbond/package_control_channel/pull/8522
This will likely take a few days to be merged in, so in the meantime, the best way to get these updates is by manually installing from here.

I will leave this issue open for the time being for anyone to submit feedback in case they run into problems but will presume the issue is resolved once the package control channel has been updated.

**Comment by easyfrog** [comment]
@corneliusio Thanks for your work. I download 3.5.2 version to my sublime's package folder, but this bracket red background issue still have

**Comment by ehzro3** [comment]
<img width="431" alt="Screen Shot 2022-08-10 at 11 04 30" src="https://user-images.githubusercontent.com/40330010/183939435-365ea873-a04a-4232-998e-06e0552ebd91.png">
I was about to ask the same thing 🤣
